### ISSUE TITLE
Where is the Login page?

### ISSUE THREAD

**Issue by jeff-ridgeway** [tailwindcomponents/dashboard-template#1]
I've successfully git cloned the repository and am running the code on my local machine. However, when I see the snapshots in the README in particular, the Login Page, I can't access it from the template as is. Is there a way to access the Login Page to be able to look at it as well as make modifications as necessary? 

BTW this template is awesome and is just what I was looking for in my upcoming project! Thanks! 😃

**Comment by khatabwedaa** [comment]
You can access it in /login url try `localhost:3000/login` , and will get the page.

Thanks @jeff-ridgeway 🤩✨
