### ISSUE TITLE
How can I make the sidebar of dashboard goes to the right side?

### ISSUE THREAD

**Issue by jeanali** [tailwindcomponents/dashboard-template#3]
Hi, thank you for this amazing work.
I have a small problem with the sidebar when I just convert it from the left to the right side the design broke down! cloud you please help? :( 

my problem in **sidebar.blade.php**  line 3 when just make it right not left

**Comment by khatabwedaa** [comment]
Can you send your code and I will take look

**Comment by jeanali** [comment]
@khatabwedaa 

Here is my code, ```rtl:right-0``` I just add this one when the language is English it took the main one which is  ``` left-0``` but when I  make it right the design broke down!
 
This is the line: in **sidebar.blade.php**
```
<div :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'"
    class="fixed z-30 inset-y-0 left-0 rtl:right-0 w-64 duration-300 transform bg-sidebar-color overflow-y-auto lg:translate-x-0 lg:static lg:inset-0">
.....
```

**Comment by khatabwedaa** [comment]
I think you have to add RTL direction to all page and will work for you

**Comment by jeanali** [comment]
@khatabwedaa  I already add it, via [this](https://github.com/RonMelkhior/tailwindcss-dir) but still in the sidebar.
can you please give me your email to send your full example?

**Comment by yogesh-gohil** [comment]
i think you need to use like this

**ltr:left-0 rtl:right-0**
