### ISSUE TITLE
Menu's open and close on every page load

### ISSUE THREAD

**Issue by MACscr** [tailwindcomponents/dashboard-template#4]
When in a mobile view (easy to produce by changing the window size) where there is a top bar and the sidebar is hidden, every time you load a page or refresh, the sidebar nav flickers open and then close. Im getting the same with the dropdown mobile top right menu too, but for some reason thats not happening in your demo, so lets just stick with the left main sidebar navigation that happens both in your demo and on my install as well.

**Comment by khatabwedaa** [comment]
Hey @MACscr, You just have to add x-clock to your sidebar and dropdowns check this [commit](https://github.com/tailwindcomponents/dashboard/commit/5f422cf3b65321e3ea6f765b14acf1f6652def4b)
