### ISSUE TITLE
dont show correctly in laravel 9

### ISSUE THREAD

**Issue by NZ62AN** [tailwindcomponents/dashboard-template#5]
hi
When running in Laravel 9, it shows where the problem is as shown below؟
![Capture](https://user-images.githubusercontent.com/42322285/187719669-c772b04b-bb1f-40d8-b0c7-00abc4d19c94.PNG)

**Comment by Supernova3339** [comment]
do npm run build for vite for mix do npm run dev

**Comment by Supernova3339** [comment]
Please reply and let me know if I solved your issue, to help others.
